version: "3.8"
services:

  mysql:
    image: mysql:8.0
    container_name: smartcity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_city_users
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  mysql-vehicles:
    image: mysql:8.0
    container_name: smartcity-mysql-vehicles
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vehiclepassword
      MYSQL_DATABASE: smart_city_vehicles
      MYSQL_USER: vehicleuser
      MYSQL_PASSWORD: vehiclepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-vehicles-data:/var/lib/mysql


  mysql-traffic:
    image: mysql:8.0
    container_name: smartcity-mysql-traffic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: roottraffic
      MYSQL_DATABASE: traffic_signal_db
      MYSQL_USER: trafficuser
      MYSQL_PASSWORD: trafficpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-traffic-data:/var/lib/mysql


  mysql-violation:
    image: mysql:8.0
    container_name: smartcity-mysql-violation
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: violationpassword
      MYSQL_DATABASE: violation_db
      MYSQL_USER: violationuser
      MYSQL_PASSWORD: violationpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql-violation-data:/var/lib/mysql

  mysql-payment:
    image: mysql:8.0
    container_name: smartcity-mysql-payment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: paymentpassword
      MYSQL_DATABASE: payment_db
      MYSQL_USER: paymentuser
      MYSQL_PASSWORD: paymentpassword
    ports:
      - "3310:3306"
    volumes:
      - mysql-payment-data:/var/lib/mysql

  mysql-notification:
    image: mysql:8.0
    container_name: smartcity-mysql-notification
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notifpassword
      MYSQL_DATABASE: notification_db
      MYSQL_USER: notifUser
      MYSQL_PASSWORD: notifPassword
    ports:
      - "3311:3306"
    volumes:
      - mysql-notification-data:/var/lib/mysql


  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

  kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
        - zookeeper

volumes:
  mysql-data:
  mysql-vehicles-data:
  mysql-traffic-data:
  mysql-violation-data:
  mysql-payment-data:
  mysql-notification-data: