version: "3.8"
services:
  # User Service MySQL
  mysql:
    image: mysql:8.0
    container_name: smartcity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_city_users
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Vehicle Service MySQL
  mysql-vehicles:
    image: mysql:8.0
    container_name: smartcity-mysql-vehicles
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vehiclepassword
      MYSQL_DATABASE: smart_city_vehicles
      MYSQL_USER: vehicleuser
      MYSQL_PASSWORD: vehiclepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-vehicles-data:/var/lib/mysql

  # Traffic Signal Service MySQL
  mysql-traffic:
    image: mysql:8.0
    container_name: smartcity-mysql-traffic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: roottraffic
      MYSQL_DATABASE: traffic_signal_db
      MYSQL_USER: trafficuser
      MYSQL_PASSWORD: trafficpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-traffic-data:/var/lib/mysql

volumes:
  mysql-data:
  mysql-vehicles-data:
  mysql-traffic-data:
