version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: smartcity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_city_users
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
